# Generated by Django 3.1.2 on 2020-11-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(default='others', max_length=20)),
                ('character', models.CharField(max_length=10, null=True)),
                ('img_path', models.TextField(null=True)),
            ],
        ),
    ]
