# Generated by Django 3.1.2 on 2020-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='character',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
