name: decrypt_enviroment

on:
  push:
    branches:
      - main

jobs:
  decrypt_enviroment:
    name: decrypt env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt env.json.gpg
        run: ./back_end/_decryptenv.sh
        env:
          ENV_DECRYPE_PW: ${{ secrets.ENV_DECRYPE_PW }}
